import Head from 'next/head'
import Banner from '../components/Banner'
import Client from '../components/Client'
import Hero from '../components/Hero'
import Navbar from '../components/Navbar'
import Relased from '../components/Relased'
import Relased2 from '../components/Relased2'
import SuperRare from '../components/SuperRare'
import Footer from '../components/Footer'
import CopyRight from '../components/CopyRight'
import Top from '../components/Top'

// import images

import relaseImg from '../public/assets/release1.png'
import sign from '../public/assets/signup.png'
import HeroImg from '../public/assets/home.png'


export default function Home() {
  return (
    <>
      <Head>
        <title>NFT-WEBSITE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Hero img={HeroImg}/>
      <Banner/>
      <Client/>
      <SuperRare/>
      <Relased img={sign}/>
      <Relased2 img={relaseImg}/>
      <Hero img={sign}/>
      <Footer/>
      <CopyRight/>
      <Top/>
    </>
  )
}
